services:
  app:
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.4.0-alpine3.20
    ports:
      - 6379:6379
    volumes:
      - redisdata:/redis/data

  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'test'
    volumes:
      - postgresdata:/postgresql/data

volumes:
  redisdata:
  postgresdata:
